---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# User file database https://www.authelia.com/reference/guides/passwords/#yaml-format
# Generate passwords https://www.authelia.com/reference/guides/passwords/#passwords

# List of users
users:
  # Username
  authelia:
    disabled: false
    displayname: "Authelia Admin"
    # IMPORTANT: Replace the current password 'authelia' with a securely hashed password.
    # Generate a hashed password by running:
    # `docker run -it authelia/authelia:latest authelia crypto hash generate argon2`
    # Then, update the password below with your newly hashed password.
    password: "$6$rounds=50000$BpLnfgDsc2WD8F2q$Zis.ixdg9s/UOJYrs56b5QEZFiZECu0qZVNsIYxBaNJ7ucIL.nlxVCT5tqh8KHG8X4tlwCFm5r6NTOZZ5qRFN/"  # yamllint disable-line rule:line-length
    email: autheliaadmin@heyvaldemar.net
    groups:
      - admins
      - dev
